[package]
authors = ["x1a0t <405028157@qq.com>", "DarkSky <darksky2048@gmail.com>"]
edition = "2021"
license = "MIT"
name    = "y-octo-utils"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bench = ["regex"]
fuzz  = ["arbitrary", "phf"]

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"], optional = true }
phf       = { version = "0.11", features = ["macros"], optional = true }
regex     = { version = "1.5", optional = true }
y-octo    = { workspace = true }
y-sync    = "=0.3.0"
yrs       = "=0.16.5"

[dev-dependencies]
proptest         = "1.2"
proptest-derive  = "0.4"

[[bin]]
name = "bench_result_render"
path = "bin/bench_result_render.rs"
