name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEBUG: napi:*
  COVERAGE: true

jobs:
  build-node:
    name: Build Storage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C debuginfo=1"
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          target: "x86_64-unknown-linux-gnu"
      - name: Build node binding
        run: yarn build:node
      - name: Upload y-octo.node
        uses: actions/upload-artifact@v3
        with:
          name: y-octo.node
          path: ./y-octo-node/y-octo.node
          if-no-files-found: error

  node-binding-test:
    name: Node Binding Test
    runs-on: ubuntu-latest
    needs: build-node
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Download y-octo.node
        uses: actions/download-artifact@v3
        with:
          name: y-octo.node
          path: ./y-octo-node
      - name: Run node binding tests
        run: yarn test:node:coverage
        working-directory: y-octo-node
      - name: Upload server test coverage results
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./y-octo-node/.coverage/lcov.info
          flags: node-binding-test
          name: y-octo
          fail_ci_if_error: false
